# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - AI-service
    tags:
      - 'v*'

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/src/server2
      - name: Build with Maven
        run: mvn clean package --file $GITHUB_WORKSPACE/src/server2/pom.xml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # 指定Node.js的版本
      - name: Install dependencies
        run: npm install
        working-directory: ./src/client-side-application # 指定前端项目的目录
      - name: Build frontend
        run: npm run build
        working-directory: ./src/client-side-application # 指定前端项目的目录

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: ./release/SYSU_LACR.jar

      - name: Archive and Upload Frontend Artifact
        run: zip -r build-frontend.zip ./src/client-side-application/build
        - uses: actions/upload-artifact@v2
          with:
            name: frontend-artifact
            path: ./release/build-frontend.zip

  release:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Backend Artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact
          path: ./release

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: ./release