# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: vue-spring

on:
  push:
    branches:
      - AI-service
    tags:
      - 'v*'

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}/src/server2
      - name: Build with Maven
        run: mvn clean package --file $GITHUB_WORKSPACE/src/server2/pom.xml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./src/client-side-application
      - name: Build frontend
        run: npm run build
        working-directory: ./src/client-side-application

      - name: Prepare Artifacts for Packaging
        run: |
          mkdir -p ./release-package/frontend
          cp ./src/server2/target/SYSU_LACR.jar ./release-package/
          cp -r ./src/client-side-application/build/* ./release-package/frontend/

      - name: Create Combined ZIP
        run: |
          cd release-package
          zip -r ../release-package.zip .

      - name: Upload Combined ZIP Artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-artifact
          path: release-package.zip

  release:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Combined Artifact
        uses: actions/download-artifact@v2
        with:
          name: combined-artifact
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Combined ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/release-package.zip
          asset_name: release-package.zip
          asset_content_type: application/zip
